import {Injectable} from '@angular/core';

@Injectable()
export class filterService{
    getFilters(){
        return this.filters;
    }
    filters = {
            'Allpass':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                      'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                      'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'allpass'},
            'Notch':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                      'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                      'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'notch'},
            'Peaking':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                      'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                      'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'peaking'},
            'Highshelf':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                      'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                      'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'highshelf'},
            'Lowshelf':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                      'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                      'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'lowshelf'},
            'Bandpass':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                      'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                      'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'bandpass'},
            'Lowpass':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                      'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                      'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'lowpass'},
            'Highpass':{'displayed': {'frequency':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                        'Q':{'value': 0.001, 'min':0.001, 'max':100, 'log':false},
                                        'gain':{'value': -40, 'min':-40, 'max':40, 'log':false}},
                         'type':'highpass'},
            'Bitcrusher': {'displayed': {'bits':{'value': 1, 'min':1, 'max':16, 'log':true},
                                          'normfreq':{'value': 0, 'min':0, 'max':1, 'log':true},
                                          'bufferSize':{'value': 256, 'min':256, 'max':16384, 'log':true}},
                            'type': 'none'},
            'Chorus': {'displayed': {'rate':{'value': 0, 'min':0.01, 'max':8, 'log':true},
                                      'feedback':{'value': 0, 'min':0, 'max':1, 'log':false},
                                      'delay':{'value': 0, 'min':0, 'max':1, 'log':true}},
                        'type': 'none'},
            'Delay': {'displayed': {'wetLevel':{'value': 0, 'min':0, 'max':2, 'log':true},
                                    'feedback':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'delayTime':{'value': 0, 'min':0, 'max':1, 'log':true},
                                    'dryLevel':{'value': 0, "min":0, 'max':2, 'log':false},
                                    'cutoff':{'value':20, 'min':20, 'max':22050, 'log':true},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'Phaser': {'displayed': {'rate':{'value': 0.01, 'min':0.01, 'max':8, 'log':false},
                                    'depth':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'feedback':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'stereoPhase':{'value': 0, 'min':0, 'max':180, 'log':false},
                                    'baseModulationFrequency':{'value':500, 'min':500, 'max':1500, 'log':true},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'Overdrive': {'displayed': {'outputGain':{'value': 0., 'min':1, 'max':1, 'log':false},
                                    'drive':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'curveAmount':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'algorithmIndex':{'value': 0, 'min':0, 'max':5, 'log':false},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'Compressor': {'displayed': {'threshold':{'value': 0.01, 'min':0.01, 'max':8, 'log':false},
                                    'makeupGain':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'attack':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'release':{'value': 0, 'min':0, 'max':180, 'log':false},
                                    'ratio':{'value':500, 'min':500, 'max':1500, 'log':true},
                                    'knee':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    //'automakeup':{'value': true, 'min':false, 'max':true, 'log':false},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'Convolver': {'displayed': {'highCut':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                    'lowCut':{'value': 20, 'min':20, 'max':22050, 'log':true},
                                    'dryLevel':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'wetLevel':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'level':{'value':0, 'min':0, 'max':1, 'log':true},
                                    //'impulse':{'value': "impulses/impulse_rev.wav"},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'Cabinet': {'displayed': {'makeupGain':{'value': 0.01, 'min':0.01, 'max':8, 'log':false},
                                    //'impulsePath':{'value': "impulses/impulse_rev.wav"},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'Tremolo': {'displayed': {'intensity':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'rate':{'value': 0.001, 'min':0.001, 'max':8, 'log':false},
                                    'stereoPhase':{'value': 0, 'min':0, 'max':180, 'log':false},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'WahWah': {'displayed': {//'automode':{'value': true},
                                    'baseFrequency':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'excursionOctaves':{'value': 0, 'min':0, 'max':6, 'log':false},
                                    'sweep':{'value': 1, 'min':1, 'max':100, 'log':false},
                                    'resonance':{'value':500, 'min':500, 'max':1500, 'log':true},
                                    'sensivity':{'value': -1, 'min':-1, 'max':1, 'log':false},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'MoogFilter': {'displayed': {'cutoff':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'resonance':{'value': 0, 'min':0, 'max':4, 'log':false},
                                    'bufferSize':{'value': 256, 'min':256, 'max':16384, 'log':false},
                                    //'bypass':{'value':0, 'min':0, 'max':1, 'log':false}
                                    },
                        'type': 'none'},
            'pingPongDelay': {'displayed': {'wetLevel':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'feedback':{'value': 0, 'min':0, 'max':1, 'log':false},
                                    'delayTimeLeft':{'value': 1, 'min':1, 'max':10000, 'log':false},
                                    'delayTimeRight':{'value': 1, 'min':1, 'max':10000, 'log':false},
                                    },
                        'type': 'none'},
            }
}